#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# This test case is to test CSEvalClient works with the same setup of users. 
# For that purpose, the test needs to create some models and data in the Examples directories as expected by CSEvalClient.
# These files are removed by Jenkins during workspace cleanup.

ImageDir=$TEST_ROOT_DIR/../../Examples/Image
MnistDir=$ImageDir/MNIST
DataDir=$MnistDir/Data
ConfigDir=$MnistDir/Config
OutputDir=$MnistDir/Output

# Train model for evaluation
[ -d $OutputDir ] || mkdir $OutputDir || exit 1
[ -d $OutputDir/Models ] && rm -rf $OutputDir/Models
DeleteModelsAfterTest=0

[ -f $ConfigDir/01_OneHidden.cntk ] || exit 1

cntkrun 01_OneHidden.cntk "command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || exit 1
 
if [ "$OS" == "Windows_NT" ]; then
  $TEST_BIN_DIR/CPPEvalClientTest.exe
else
  $TEST_BIN_DIR/cppevalclient
fi

exit $?