#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# The eval test uses some pretrained models which is not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" == "" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo 'This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location'
  exit 1
fi

if [ "$OS" == "Windows_NT" ]; then
    ModelSourceDir=`cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY`/PreTrainedModels
else
    ModelSourceDir=$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/PreTrainedModels
fi

# Copy pretrained models to the appropriate directories
ImageDir=$TEST_ROOT_DIR/../../Examples/Image
MnistModelDir=$ImageDir/MNIST/Output/Models
ResnetModelDir=$ImageDir/Miscellaneous/ImageNet/ResNet
mkdir -p $MnistModelDir

cp $ModelSourceDir/MNIST_01_OneHidden $MnistModelDir/01_OneHidden || exit $?
cp $ModelSourceDir/MNIST_02_Convolution $MnistModelDir/02_Convolution || exit $?
cp $ModelSourceDir/ResNet_18.model $ResnetModelDir/ || exit $?

if [ "$OS" == "Windows_NT" ]; then
  cd $TEST_BIN_DIR
  ./CSEvalClientTest.exe || exit $?
else
  echo "CSEvalClientTest can only run on Windows";
  exit 1;
fi

grep -i "Inner Exception" $TEST_RUN_DIR/output.txt && exit 1	
ExitCode=0

#Delete Model data
rm -rf $ImageDir/MNIST/Output
rm -f $ResnetModelDir/ResNet_18.model

exit $ExitCode
